#!/bin/bash
## grapher -- by Patsie
# Draw a graph using an ASCII graph function from data from stdin

## Should the graph move from right to left or vice versa
right_to_left=1

## include graphing function
. ./graph.fnc

read val
data=$(for i in {1..60}; do echo $val; done)

clear

## Repeat until EOF
while read val; do
  ## Go to top left corner and print date
  echo -e "\e[H$(date)\n"

  ## Add new datapoint to graph
  if [ $right_to_left -eq 1 ]; then
    data=$(echo $data $val | cut -d' ' -f2-61)
  else
    data=$(echo $val $data | cut -d' ' -f1-60)
  fi

  ## Draw graph and wait
  graph 9 $data
done
